services:
  db:
    image: postgres:latest
    container_name: task_manager
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: